name: alabs_flutter_core
description: "alabs Flutter Core"

version: 1.2.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

  dio: ^5.3.3
  json_annotation: ^4.8.1
  logger: ^2.0.2+1

  get_it: ^7.6.4
  injectable: ^2.3.2

  dartz: ^0.10.1
  equatable: ^2.0.5

  flutter_bloc: ^8.1.3
  toast: ^0.3.0
  snackbar: ^1.0.2
  intl: ^0.18.1
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  mask_text_input_formatter: ^2.5.0
  package_info_plus: ^3.1.2
  flutter_device_type: ^0.4.0

  connectivity_plus: ^5.0.2
  pointycastle: ^3.7.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: any
  build_runner: any

flutter:

  uses-material-design: true
